version: '3.3'
services: 
    react:
        build: frontend/
        ports:
         - "3000:3000"
    influxdb:
        build: influxdb/
        ports: 
         - "8086:8086"
        # volumes: 
        #  - $PWD/data:/var/lib/influxdb2
        #  - $PWD/config/config.yml:/etc/influxdb2/config.yml
        # - .:./
    