version: '3.3'
services: 
    frontend:
        build: frontend/
        ports:
         - "3000:3000"
        environment:
         CHOKIDAR_USEPOLLING: "true"
        volumes:
         - $PWD/frontend:/frontend/frontend
        #  - $PWD/frontend/node_modules
    mongodb:
        image: mongo
        ports:
          - "27017:27017"
        environment: 
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: mongoadmin
          MONGO_INITDB_DATABASE: can_data_db
    api:
        build: api/
        network_mode: "host"

        # ports:
        #   - "8000:8000"
        volumes:
          - $PWD/api:/api
        # links:
        #   - mongodb
    influxdb:
        build: influxdb/
        ports: 
         - "8086:8086"
        volumes: 
         - $PWD/influxdb/data:/var/lib/influxdb2
         - $PWD/influxdb/configs:/.influxdbv2/configs
    
    