version: '3.3'
services: 
    react:
        build: frontend/
        ports:
         - "3000:3000"
        environment:
         CHOKIDAR_USEPOLLING: "true"
        volumes:
         - $PWD/frontend:/frontend
         - $PWD/frontend/node_modules
    influxdb:
        build: influxdb/
        ports: 
         - "8086:8086"
        volumes: 
         - $PWD/influxdb/data:/var/lib/influxdb2
         - $PWD/influxdb/configs:/.influxdbv2/configs
    