version: '3.3'
services:
    frontend:
        build: frontend/
        ports:
         - "127.0.0.1:3000:3000"
        environment:
         CHOKIDAR_USEPOLLING: "true"
        volumes:
         - ./frontend:/frontend
        # - $PWD/frontend/node_modules
    mongodb:
        image: mongo
        ports:
          - "127.0.0.1:27017:27017"
        environment: 
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: mongoadmin
          MONGO_INITDB_DATABASE: can_data_db
    api:
        build: api/
        ports:
          - "127.0.0.1:8000:8000"
        volumes:
          - ./api:/api
        links:
          - mongodb
    influxdb:
        build: influxdb/
        ports: 
         - "127.0.0.1:8086:8086"
        volumes: 
         - ./influxdb/data:/var/lib/influxdb2
         - ./influxdb/configs:/.influxdbv2/configs
    
    