# Generated by Django 3.0 on 2021-06-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bustype', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
                ('bitrate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DbcFile',
            fields=[
                ('FileName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('FileData', models.TextField()),
            ],
        ),
    ]
