# Generated by Django 3.0 on 2021-05-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbcFile',
            fields=[
                ('FileName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('FileData', models.TextField()),
            ],
        ),
    ]
