# Generated by Django 3.0 on 2021-07-11 17:35

import can_server.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('can_server', '0002_auto_20210619_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cansettings',
            name='bitrate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cansettings',
            name='bustype',
            field=models.CharField(max_length=100, validators=[can_server.models.validate_alpha]),
        ),
        migrations.AlterField(
            model_name='cansettings',
            name='channel',
            field=models.CharField(max_length=100, validators=[can_server.models.validate_alpha]),
        ),
    ]
