# Generated by Django 3.0 on 2021-11-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('can_server', '0003_auto_20210711_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbcfile',
            name='Selected',
            field=models.BooleanField(default=False),
        ),
    ]
