# Generated by Django 3.0.5 on 2021-02-19 00:43

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanServerDecoded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datetime', models.DateTimeField()),
                ('Name', models.CharField(max_length=100)),
                ('Sender', models.CharField(max_length=100)),
                ('Data', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='CanServerRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DecimalField(decimal_places=3, max_digits=20)),
                ('ArbitrationID', models.PositiveIntegerField()),
                ('DLC', models.PositiveSmallIntegerField()),
                ('Data', models.BinaryField()),
            ],
        ),
    ]
