name: CI

on:
  # Run on all pull requests and all pushes to main
  push:
    branches: [ main ]
  pull_request:

  # Allow running this workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install pipenv
        run: |
          pip3 install --user pipenv
          pip3 install --user pylint
          pip3 install --user autopep8

      - name: Setup Redis, Mongo 
        run: |
          bash mongo_setup.sh

      - name: Install backend dependencies 
        run: |
          cd api
          pipenv install

      - name: Install frontend dependencies
        run: |
          cd ..
          cd client 
          npm install
