name: CI

on:
  # Run on all pull requests and all pushes to main
  push:
    branches: [ main ]
  pull_request:

  # Allow running this workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Local fix for Act
        run: |
          # Hack to get setup-python to work on act
          # (see https://github.com/nektos/act/issues/251)
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install pipenv
        run: |
          sudo apt-get update
          pip3 install --user pipenv
          pip3 install --user pylint
          pip3 install --user autopep8

      - name: Setup Node
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install MongoDB
        run: |
          bash mongo_setup.sh

      - name: Install Redis
          sudo add-apt-repository ppa:chris-lea/redis-server
          sudo apt-get update
          sudo apt -y install redis-server

      - name: Install backend dependencies 
        run: |
          cd backend
          pipenv install

      - name: Install frontend dependencies
        run: |
          cd ~
          cd frontend 
          npm install
